
language: python
python:
- "2.7"

before_install:
# Install Google AppEngine Python SDK.
# Not installed in the build dir to avoid include it in the deploy.
- cd ..
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.25.zip -nv
- unzip -q google_appengine_1.9.25.zip
- export GAE_PATH="$(pwd)/google_appengine"
- export PYTHONPATH=$GAE_PATH:$PYTHONPATH
- export PATH=$GAE_PATH:$PATH
- cd $TRAVIS_BUILD_DIR

install:
# Install Python dependencies (using pip).
- ./build.sh

script:
# Run all tests
- python tests/suite.py

after_success:
- echo "Test Success!"
- echo "Deploying..."
# Put secret tokens in the code.
# Replace YOUR-TELEGRAM-BOT-TOKEN string by the value of env var TELEGRAM_TOKEN.
- sed -Ei "s/YOUR-TELEGRAM-BOT-TOKEN/$TELEGRAM_TOKEN/g" telegram_token.py
# APP_TOKEN value can be obtainde from ~/.appcfg_oauth2_tokens local file.
# Copy "refresh_token" value entry.
- appcfg.py --oauth2_refresh_token=$APP_TOKEN --application=$APP_ID --version=$APP_VERSION update .
