
language: python
python:
- "2.7"

env:
- LIB_DIR=lib

before_script:
# Install Google AppEngine Python SDK
- cd $LIB_DIR
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.25.zip -nv
- unzip -q google_appengine_1.9.25.zip
- export PYTHONPATH="$(pwd)/google_appengine"
- cd $TRAVIS_BUILD_DIR

install:
# Install Python dependencies (using pip)
- ./build.sh

script:
# Run all tests
- python tests/suite.py
